version: "3.8"

services:
  pg:
    image: bitnami/postgresql:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=m.tasks
    volumes:
      - pgdata:/var/lib/postgresql/data

 
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    environment:
      - DATABASE_URL=postgresql://docker:docker@localhost:5432/m.tasks
    depends_on:
      - pg